
# feeder
feeder: feeders.feeder_jb.Feeder
train_feeder_args:
  data_path: ['./data/train_joint.npy','./data/train_bone.npy']
  label_path: ./data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ['./data/val_joint.npy','./data/val_bone.npy']
  label_path: ./data/val_label.npy

# model 
model: model.chase.STSANet.stsanet.Model
model_args:
  len_parts: 3
  num_frames: 300
  num_joints: 17
  num_classes: 155
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 6
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64]]

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True