
# feeder
feeder: feeders.feeder_rgb.Feeder
train_feeder_args:
  data_path: train
  label_path: ./data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: val
  label_path: ./data/val_label.npy

# model
model: model.fftTran.Model
model_args:
  num_class: 155



#optim
weight_decay: 0.0001
base_lr: 0.01
step: [30, 40]

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True